// src/core/excitation.js

const TWO_PI = Math.PI * 2;
const DEFAULT_VELOCITY_LP_Q = 0.404;
const DEFAULT_FIXED_LP_Q = 0.45;
const DEFAULT_FIXED_LP_CUTOFF = 3500;
// Pd hip~ 沒有顯式 Q，這裡先用常見的 Butterworth 近似
const DEFAULT_HP_Q = Math.SQRT1_2;

/**
 * Main entry:
 * Build a piano-like excitation buffer from
 * tonal burst + noise burst + filter chain.
 */
export function generatePianoExcitation({
  freq,
  velocity,
  sampleRate,
  tonalGain = 1.0,
  noiseGain = 1.0,
  tonalOptions = {},
  noiseOptions = {},
  velocityLpQ = DEFAULT_VELOCITY_LP_Q,
  fixedLpCutoff = DEFAULT_FIXED_LP_CUTOFF,
  fixedLpQ = DEFAULT_FIXED_LP_Q,
  hpQ = DEFAULT_HP_Q,
  maxDurationSec = 0.08,
  minDurationSec = 0.004,
}) {
  validateFreq(freq);
  validateSampleRate(sampleRate);

  const tonal = generateTonalBurst({
    freq,
    velocity,
    sampleRate,
    maxDurationSec,
    minDurationSec,
    ...tonalOptions,
  });

  const noise = generateNoiseBurst({
    freq,
    velocity,
    sampleRate,
    maxDurationSec,
    minDurationSec,
    ...noiseOptions,
  });

  const length = Math.max(tonal.length, noise.length);
  const out = new Float32Array(length);

  for (let i = 0; i < length; i++) {
    out[i] =
      (i < tonal.length ? tonal[i] * tonalGain : 0) +
      (i < noise.length ? noise[i] * noiseGain : 0);
  }

  // 1) velocity-dependent lowpass
  const velocityCutoff = velocityToCutoffHz(velocity);
  applyBiquadLowpassInPlace(out, velocityCutoff, velocityLpQ, sampleRate);

  // 2) three fixed lowpasses: 3500 Hz, Q=0.45
  applyBiquadLowpassInPlace(out, fixedLpCutoff, fixedLpQ, sampleRate);
  applyBiquadLowpassInPlace(out, fixedLpCutoff, fixedLpQ, sampleRate);
  applyBiquadLowpassInPlace(out, fixedLpCutoff, fixedLpQ, sampleRate);

  // 3) highpass at freq / 2
  applyBiquadHighpassInPlace(out, freq * 0.5, hpQ, sampleRate);

  return out;
}

/**
 * First-pass tonal burst:
 * sine burst with short attack and velocity-shaped decay curve.
 *
 * Simplified from the Pd tonal branch:
 * - duration ~= cycles / freq
 * - fast attack
 * - envelope exponent = 2 - vNorm
 *
 * This version intentionally does NOT yet include the Pd-style
 * skew term (1 - 2u). Easy to add later.
 */
export function generateTonalBurst({
  freq,
  velocity,
  sampleRate,
  gain = 0.25,
  attackMs = 2,
  cycles = 8,
  maxDurationSec = 0.08,
  minDurationSec = 0.004,
}) {
  validateFreq(freq);
  validateSampleRate(sampleRate);

  const vel = clamp(velocity, 1, 127);
  const vNorm = (vel - 1) / 126;
  const exponent = 2 - vNorm;

  const attackSec = Math.max(0, attackMs * 0.001);

  let durationSec = cycles / freq;
  durationSec = clamp(durationSec, minDurationSec, maxDurationSec);

  const length = Math.max(1, Math.ceil(durationSec * sampleRate));
  const attackSamples = Math.min(
    length,
    Math.max(1, Math.round(attackSec * sampleRate))
  );

  const out = new Float32Array(length);

  const phaseInc = (TWO_PI * freq) / sampleRate;
  let phase = 0;

  for (let i = 0; i < length; i++) {
    const env = shapedAttackDecayEnvelope(i, length, attackSamples, exponent);
    out[i] = Math.sin(phase) * gain * env;
    phase += phaseInc;
  }

  return out;
}

/**
 * Noise burst modeled after the Pd branch:
 * - noise source scaled by 2
 * - envelope generated by a one-pole smoothing process
 * - input step: 1 for first 2 ms, then 0
 * - shape with exponent = 2 - vNorm
 *
 * This is closer to the Pd logic than a simple linear envelope.
 */
export function generateNoiseBurst({
  freq,
  velocity,
  sampleRate,
  gain = 1.0,
  attackWindowMs = 2,
  lowCutoffHz = 1000 / 240, // ~4.1667 Hz, from the Pd patch
  maxDurationSec = 0.08,
  minDurationSec = 0.004,
}) {
  validateFreq(freq);
  validateSampleRate(sampleRate);

  const vel = clamp(velocity, 1, 127);
  const vNorm = (vel - 1) / 126;
  const exponent = 2 - vNorm;

  let durationSec = 8 / freq;
  durationSec = clamp(durationSec, minDurationSec, maxDurationSec);

  const length = Math.max(1, Math.ceil(durationSec * sampleRate));
  const attackSamples = Math.max(1, Math.round((attackWindowMs * 0.001) * sampleRate));

  const out = new Float32Array(length);

  // one-pole smoothing coefficient
  const cutoff = clamp(lowCutoffHz, 1e-6, sampleRate * 0.5 * 0.99);
  const alpha = 1 - Math.exp((-TWO_PI * cutoff) / sampleRate);

  let y = 0;

  for (let i = 0; i < length; i++) {
    const x = i < attackSamples ? 1 : 0;
    y += alpha * (x - y);

    const env = Math.pow(clamp(y, 0, 1), exponent);
    const noise = ((Math.random() * 2) - 1) * 2;

    out[i] = noise * env * gain;
  }

  return out;
}

/**
 * Velocity mapping from the Pd patch:
 * vNorm = (v - 1) / 126
 * midi = 70 + 50 * vNorm^1.25
 * cutoff = mtof(midi)
 */
export function velocityToCutoffHz(velocity) {
  const vel = clamp(velocity, 1, 127);
  const vNorm = (vel - 1) / 126;
  const midi = 70 + 50 * Math.pow(vNorm, 1.25);
  return mtof(midi);
}

export function mtof(midi) {
  return 440 * Math.pow(2, (midi - 69) / 12);
}

/**
 * In-place RBJ lowpass biquad.
 */
export function applyBiquadLowpassInPlace(buffer, cutoffHz, q, sampleRate) {
  const coeffs = makeBiquadLowpassCoeffs(cutoffHz, q, sampleRate);
  applyBiquadInPlace(buffer, coeffs);
}

/**
 * In-place RBJ highpass biquad.
 */
export function applyBiquadHighpassInPlace(buffer, cutoffHz, q, sampleRate) {
  const coeffs = makeBiquadHighpassCoeffs(cutoffHz, q, sampleRate);
  applyBiquadInPlace(buffer, coeffs);
}

/**
 * Generic in-place Direct Form I / transposed-ish simple biquad sample loop.
 * Coeffs are assumed already normalized by a0.
 */
export function applyBiquadInPlace(buffer, coeffs) {
  const { b0, b1, b2, a1, a2 } = coeffs;

  let x1 = 0;
  let x2 = 0;
  let y1 = 0;
  let y2 = 0;

  for (let i = 0; i < buffer.length; i++) {
    const x0 = buffer[i];
    const y0 = b0 * x0 + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2;

    buffer[i] = y0;

    x2 = x1;
    x1 = x0;
    y2 = y1;
    y1 = y0;
  }
}

export function makeBiquadLowpassCoeffs(cutoffHz, q, sampleRate) {
  validateSampleRate(sampleRate);

  const nyquist = sampleRate * 0.5;
  const fc = clamp(cutoffHz, 1e-6, nyquist * 0.99);
  const Q = Math.max(1e-6, q);

  const omega = TWO_PI * fc / sampleRate;
  const cosw = Math.cos(omega);
  const sinw = Math.sin(omega);
  const alpha = sinw / (2 * Q);

  const b0 = (1 - cosw) * 0.5;
  const b1 = 1 - cosw;
  const b2 = (1 - cosw) * 0.5;
  const a0 = 1 + alpha;
  const a1 = -2 * cosw;
  const a2 = 1 - alpha;

  return normalizeBiquad(b0, b1, b2, a0, a1, a2);
}

export function makeBiquadHighpassCoeffs(cutoffHz, q, sampleRate) {
  validateSampleRate(sampleRate);

  const nyquist = sampleRate * 0.5;
  const fc = clamp(cutoffHz, 1e-6, nyquist * 0.99);
  const Q = Math.max(1e-6, q);

  const omega = TWO_PI * fc / sampleRate;
  const cosw = Math.cos(omega);
  const sinw = Math.sin(omega);
  const alpha = sinw / (2 * Q);

  const b0 = (1 + cosw) * 0.5;
  const b1 = -(1 + cosw);
  const b2 = (1 + cosw) * 0.5;
  const a0 = 1 + alpha;
  const a1 = -2 * cosw;
  const a2 = 1 - alpha;

  return normalizeBiquad(b0, b1, b2, a0, a1, a2);
}

function normalizeBiquad(b0, b1, b2, a0, a1, a2) {
  return {
    b0: b0 / a0,
    b1: b1 / a0,
    b2: b2 / a0,
    a1: a1 / a0,
    a2: a2 / a0,
  };
}

function shapedAttackDecayEnvelope(i, length, attackSamples, exponent) {
  let e;

  if (i < attackSamples) {
    e = i / attackSamples;
  } else {
    const decayDenom = Math.max(1, length - attackSamples);
    e = 1 - (i - attackSamples) / decayDenom;
  }

  e = clamp(e, 0, 1);
  return Math.pow(e, exponent);
}

function validateFreq(freq) {
  if (!Number.isFinite(freq) || freq <= 0) {
    throw new Error(`Invalid freq: ${freq}`);
  }
}

function validateSampleRate(sampleRate) {
  if (!Number.isFinite(sampleRate) || sampleRate <= 0) {
    throw new Error(`Invalid sampleRate: ${sampleRate}`);
  }
}

function clamp(x, min, max) {
  return Math.max(min, Math.min(max, x));
}